# Generated by Django 6.0.2 on 2026-02-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="types",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tracker.type"
            ),
        ),
    ]
