# Generated by Django 6.0.2 on 2026-02-12 08:09

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('tracker.Task')
    for task in Task.objects.all():
        task.types.add(task.type)

def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('tracker.Task')
    for task in Task.objects.all():
        task.type = task.types.first()

class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0002_task_types"),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
