# Generated by Django 6.0.2 on 2026-02-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_auto_20260212_1309"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="type",
        ),
    ]
