# Generated by Django 6.0.1 on 2026-01-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("acitve", "Активная"), ("inactive", "Неактивна")],
                default="active",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
