# Generated by Django 6.0.1 on 2026-01-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=100, verbose_name="Электронная почта"),
                ),
                (
                    "text",
                    models.TextField(max_length=3000, verbose_name="Текст записи"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_changed_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активно"), ("blocked", "Заблокировано")],
                        default="active",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
