# Generated by Django 6.0.1 on 2026-01-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, null=True),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "food"),
                            ("furniture", "furniture"),
                            ("clothes", "clothes"),
                            ("electronics", "electronics"),
                            ("pets", "pets"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
