# Generated by Django 6.0 on 2026-01-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="details",
            field=models.TextField(
                blank=True, max_length=3000, null=True, verbose_name="Детали"
            ),
        ),
    ]
