# Generated by Django 6.0 on 2026-01-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=3000, verbose_name="Описание"),
                ),
                (
                    "status",
                    models.CharField(
                        default="New", max_length=200, verbose_name="Статус"
                    ),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата выполнения"
                    ),
                ),
            ],
        ),
    ]
